#!/usr/bin/env bash
# apply.sh — one-shot enable script for the self-mem0 adapter.
#
# What it does (idempotent):
#   1. Adds self-mem0/ to PYTHONPATH for the mem0 server container via a
#      docker-compose.override.yaml (untracked).
#   2. Builds & installs the local stdio MCP bridge into a dedicated venv.
#   3. Patches the user-level mem0-plugin install (Claude Code).
#
# Designed to be safe to re-run. To undo, see revert.sh.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"

echo "=== 1. wire self_mem0 into the server container ==="
COMPOSE_OVERRIDE="$REPO/server/docker-compose.override.yaml"
if [ ! -f "$COMPOSE_OVERRIDE" ]; then
  cat > "$COMPOSE_OVERRIDE" <<YAML
# Auto-generated by self-mem0/apply.sh — safe to edit, do not commit.
# Mounts the self-mem0 package and prepends it to PYTHONPATH so the
# try/except import hooks in server/main.py and server/auth.py succeed.
services:
  mem0:
    volumes:
      - ../self-mem0:/app/self-mem0:ro
    environment:
      - PYTHONPATH=/app/self-mem0:/app
YAML
  echo "  wrote $COMPOSE_OVERRIDE"
else
  echo "  already exists: $COMPOSE_OVERRIDE"
fi
echo "  → restart with: docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d"

echo ""
echo "=== 2. install mem0-mcp-bridge into a local venv ==="
BRIDGE_VENV="$ROOT/mcp_bridge/.venv"
if [ ! -d "$BRIDGE_VENV" ]; then
  python3 -m venv "$BRIDGE_VENV"
fi
"$BRIDGE_VENV/bin/pip" install -q -e "$ROOT/mcp_bridge"
echo "  installed: $BRIDGE_VENV/bin/mem0-mcp-bridge"
echo "  → register with your AI editor — see self-mem0/docs/self-hosted-agents.mdx"

echo ""
echo "=== 3. patch user-level mem0-plugin (Claude Code) ==="
if [ -d "$HOME/.claude/plugins/cache/mem0-plugins/mem0" ]; then
  "$ROOT/plugins/patch_mem0_plugin.sh"
else
  echo "  mem0-plugin not installed under ~/.claude/plugins — skipping"
fi

echo ""
echo "=== 4. redirect mem0-plugin MCP from mcp.mem0.ai → local stdio bridge ==="
if [ -d "$HOME/.claude/plugins/cache/mem0-plugins/mem0" ]; then
  "$ROOT/plugins/redirect_mcp.sh"
else
  echo "  mem0-plugin not installed under ~/.claude/plugins — skipping"
fi

echo ""
echo "done. Add to your shell profile:"
echo "  export MEM0_HOST=\"http://localhost:8888\""
echo "  export MEM0_API_KEY=\"<your ADMIN_API_KEY from server/.env>\""
