#!/usr/bin/env bash
# apply.sh — one-shot enable script for the self-mem0 adapter.
#
# What it does (idempotent):
#   1. Wires self-mem0/ into the mem0 server container + the mem0-mcp MCP
#      server container via a docker-compose.override.yaml (untracked).
#   2. Patches the user-level mem0-plugin install (Claude Code).
#   3. Redirects the mem0-plugin MCP config from mcp.mem0.ai → local SSE.
#
# The MCP server itself lives in ../mem0-mcp (a self-hosted fork of the
# archived mem0ai/mem0-mcp) and is built & run by docker-compose — no local
# venv install is needed.
#
# Designed to be safe to re-run. To undo, see revert.sh.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"

echo "=== 1. wire self_mem0 + mem0-mcp into docker-compose ==="
COMPOSE_OVERRIDE="$REPO/server/docker-compose.override.yaml"
if [ ! -f "$COMPOSE_OVERRIDE" ]; then
  cat > "$COMPOSE_OVERRIDE" <<YAML
# Auto-generated by self-mem0/apply.sh — safe to edit, do not commit.
# Mounts the self-mem0 package into the server container and builds the
# mem0-mcp MCP server (from ../mem0-mcp) alongside it.
services:
  mem0:
    volumes:
      - ../self-mem0:/app/self-mem0:ro
    environment:
      - PYTHONPATH=/app/self-mem0:/app
  mem0-mcp:
    build:
      context: ../mem0-mcp
    ports:
      - "9003:9003"
    environment:
      - MEM0_API_KEY=\${ADMIN_API_KEY}
      - MEM0_HOST=http://mem0:8000
      - MCP_TRANSPORT=combined
      - MCP_PORT=9003
      - MCP_HOST=0.0.0.0
    depends_on:
      mem0:
        condition: service_started
    restart: unless-stopped
YAML
  echo "  wrote $COMPOSE_OVERRIDE"
else
  echo "  already exists: $COMPOSE_OVERRIDE"
fi
echo "  → restart with: cd $REPO/server && docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d --build"

echo ""
echo "=== 2. patch user-level mem0-plugin (Claude Code) ==="
if [ -d "$HOME/.claude/plugins/cache/mem0-plugins/mem0" ]; then
  "$ROOT/plugins/patch_mem0_plugin.sh"
else
  echo "  mem0-plugin not installed under ~/.claude/plugins — skipping"
fi

echo ""
echo "=== 3. redirect mem0-plugin MCP from mcp.mem0.ai → local SSE (9003) ==="
if [ -d "$HOME/.claude/plugins/cache/mem0-plugins/mem0" ]; then
  "$ROOT/plugins/redirect_mcp.sh"
else
  echo "  mem0-plugin not installed under ~/.claude/plugins — skipping"
fi

echo ""
echo "done. Add to your shell profile:"
echo "  export MEM0_HOST=\"http://localhost:8888\""
echo "  export MEM0_API_KEY=\"<your ADMIN_API_KEY from server/.env>\""
